import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Fragment } from "react";
import { Dialog, Transition } from "@headlessui/react";
import { Pencil, Trash, CheckCircle } from "lucide-react";
const TenantActionsModal = ({ isOpen, onClose, tenant, onEdit, onDelete, onMarkPaid, }) => {
    if (!tenant)
        return null;
    return (_jsx(Transition, { show: isOpen, as: Fragment, children: _jsxs(Dialog, { onClose: onClose, className: "relative z-50", children: [_jsx(Transition.Child, { as: Fragment, enter: "ease-out duration-300", enterFrom: "opacity-0", enterTo: "opacity-100", leave: "ease-in duration-200", leaveFrom: "opacity-100", leaveTo: "opacity-0", children: _jsx("div", { className: "fixed inset-0 bg-black/30" }) }), _jsx("div", { className: "fixed inset-0 flex items-center justify-center p-4", children: _jsxs(Dialog.Panel, { className: "w-full max-w-md rounded-lg bg-white dark:bg-gray-800 shadow-lg p-6 space-y-4", children: [_jsx(Dialog.Title, { className: "text-lg font-semibold text-gray-900 dark:text-white", children: "Tenant Actions" }), _jsxs("div", { className: "space-y-1 text-sm text-gray-700 dark:text-gray-300", children: [_jsxs("p", { children: [_jsx("strong", { children: "Name:" }), " ", tenant.user.name] }), _jsxs("p", { children: [_jsx("strong", { children: "Email:" }), " ", tenant.user.email] }), _jsxs("p", { children: [_jsx("strong", { children: "Phone:" }), " ", tenant.user.phone || "N/A"] }), _jsxs("p", { children: [_jsx("strong", { children: "Room:" }), " ", tenant.room.room_number] }), _jsxs("p", { children: [_jsx("strong", { children: "Property:" }), " ", tenant.property.name] }), _jsxs("p", { children: [_jsx("strong", { children: "Status:" }), " ", tenant.lease_status] })] }), _jsxs("div", { className: "space-y-2", children: [_jsxs("button", { onClick: onEdit, className: "w-full flex items-center gap-2 bg-yellow-100 hover:bg-yellow-200 text-yellow-800 px-4 py-2 rounded-md", children: [_jsx(Pencil, { className: "w-4 h-4" }), " Edit Lease"] }), _jsxs("button", { onClick: onMarkPaid, className: "w-full flex items-center gap-2 bg-green-100 hover:bg-green-200 text-green-800 px-4 py-2 rounded-md", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), " Mark Rent as Paid"] }), _jsxs("button", { onClick: onDelete, className: "w-full flex items-center gap-2 bg-red-100 hover:bg-red-200 text-red-800 px-4 py-2 rounded-md", children: [_jsx(Trash, { className: "w-4 h-4" }), " Delete Tenant"] })] })] }) })] }) }));
};
export default TenantActionsModal;
