import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { X, ArrowRight, Smartphone, Check } from 'lucide-react';
const TrialModal = ({ selectedTier, showPayment, acceptedTerms, setAcceptedTerms, setSelectedTier, startTrial, handleMpesaPayment }) => {
    return (_jsx("div", { className: "fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fade-in", children: _jsxs("div", { className: "bg-white dark:bg-gray-900 rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl border border-gray-200 dark:border-gray-800", children: [_jsxs("div", { className: "sticky top-0 bg-white dark:bg-gray-900 p-6 border-b border-gray-200 dark:border-gray-800 flex justify-between items-center", children: [_jsxs("h2", { className: "text-2xl font-bold text-gray-900 dark:text-white", children: ["Start Your ", _jsx("span", { className: "text-primary-600", children: selectedTier.name }), " Trial"] }), _jsx("button", { onClick: () => setSelectedTier(null), className: "p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors", children: _jsx(X, { className: "w-6 h-6 text-gray-500 dark:text-gray-400" }) })] }), _jsxs("div", { className: "p-6 space-y-8", children: [_jsxs("div", { className: "bg-blue-50 dark:bg-gray-800/50 rounded-xl p-6 flex items-center", children: [_jsx("div", { className: "w-14 h-14 bg-gradient-to-br from-primary-500 to-primary-600 rounded-xl flex items-center justify-center mr-4", children: _jsx("div", { className: "text-white", children: selectedTier.icon }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold text-gray-900 dark:text-white", children: selectedTier.name }), _jsx("p", { className: "text-gray-600 dark:text-gray-300", children: selectedTier.priceMonthly === 0
                                                ? "Free"
                                                : `Ksh ${selectedTier.priceMonthly.toLocaleString()}/month` })] })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("h3", { className: "text-lg font-semibold text-gray-900 dark:text-white flex items-center", children: [_jsx(ArrowRight, { className: "w-5 h-5 mr-2 text-primary-600" }), "How Your Trial Works"] }), _jsx("div", { className: "space-y-6", children: [
                                        {
                                            title: "Instant Access",
                                            desc: `Get full access to all ${selectedTier.name} tier features immediately`
                                        },
                                        {
                                            title: "45-Day Trial Period",
                                            desc: "Explore all features for 45 days with no payment required"
                                        },
                                        {
                                            title: "Seamless M-Pesa Payment",
                                            desc: "After 45 days, we'll send an M-Pesa prompt to continue your subscription",
                                            phone: "+254 XXX XXX XXX"
                                        }
                                    ].map((item, idx) => (_jsxs("div", { className: "flex", children: [_jsxs("div", { className: "flex flex-col items-center mr-4", children: [_jsx("div", { className: "w-8 h-8 rounded-full bg-primary-100 dark:bg-primary-900/30 flex items-center justify-center", children: _jsx("div", { className: "w-2 h-2 rounded-full bg-primary-600 dark:bg-primary-400" }) }), idx < 2 && _jsx("div", { className: "w-0.5 h-full bg-gray-200 dark:bg-gray-700 mt-1" })] }), _jsxs("div", { className: "pb-6", children: [_jsx("h4", { className: "font-medium text-gray-900 dark:text-white", children: item.title }), _jsx("p", { className: "text-gray-600 dark:text-gray-300 mt-1", children: item.desc }), item.phone && (_jsxs("div", { className: "flex items-center mt-3 bg-gray-50 dark:bg-gray-800 rounded-lg p-3", children: [_jsx(Smartphone, { className: "w-5 h-5 text-primary-600 dark:text-primary-400 mr-2" }), _jsx("span", { className: "text-sm text-gray-600 dark:text-gray-300", children: item.phone })] }))] })] }, idx))) })] }), _jsx("div", { className: "pt-4 border-t border-gray-200 dark:border-gray-700", children: _jsxs("div", { className: "flex items-start cursor-pointer", onClick: () => setAcceptedTerms(!acceptedTerms), children: [_jsx("div", { className: `flex items-center justify-center w-6 h-6 rounded border mr-3 mt-0.5 transition-colors
                ${acceptedTerms
                                            ? "bg-primary-600 border-primary-600"
                                            : "border-gray-300 dark:border-gray-600 hover:border-primary-600"}`, children: acceptedTerms && _jsx(Check, { className: "w-4 h-4 text-white" }) }), _jsxs("div", { children: [_jsxs("p", { className: "text-gray-900 dark:text-white", children: ["I agree to the NyumbaSmart", " ", _jsx("span", { className: "text-primary-600", children: "Terms of Service" }), " and", " ", _jsx("span", { className: "text-primary-600", children: "Privacy Policy" })] }), _jsx("p", { className: "text-sm text-gray-500 dark:text-gray-400 mt-1", children: "Your subscription will automatically renew after the trial period unless canceled" })] })] }) })] }), _jsxs("div", { className: "sticky bottom-0 bg-white dark:bg-gray-900 p-6 border-t border-gray-200 dark:border-gray-800", children: [showPayment ? (_jsx("button", { onClick: handleMpesaPayment, className: "w-full py-3 mt-2 rounded-md text-white font-bold bg-green-600 hover:bg-green-700", children: "Pay via M-Pesa" })) : (_jsx("button", { disabled: !acceptedTerms, onClick: startTrial, className: `w-full py-3 mt-2 rounded-md text-white font-bold ${acceptedTerms
                                ? "bg-primary-600 hover:bg-primary-700"
                                : "bg-gray-400 cursor-not-allowed"}`, children: "Start Free Trial" })), _jsx("p", { className: "text-center text-sm text-gray-500 dark:text-gray-400 mt-3", children: "No payment required \u2022 Cancel anytime" })] })] }) }));
};
export default TrialModal;
