//   const tiers = [
//     {
//       name: "Mwananchi",
//       icon: <Home className="w-6 h-6" />,
//       priceMonthly: 0,
//       priceYearly: 0,
//       properties: 1,
//       rooms: 4,
//       vacancyListings: 0,
//       topOffers: 0,
//       trial: false,
//       current: activeSub?.tier === "Mwananchi",
//       description: "Perfect for individual property owners",
//       features: [
//         "Basic property management",
//         "Single property support",
//         "Room management",
//       ],
//     },
//     {
//       name: "Silver",
//       icon: <Star className="w-6 h-6" />,
//       priceMonthly: 1200,
//       priceYearly: 6000,
//       properties: 4,
//       rooms: 30,
//       vacancyListings: 2,
//       topOffers: 1,
//       trial: true,
//       current: activeSub?.tier === "Gold",
//       description: "Ideal for small property portfolios",
//       features: [
//         "Advanced analytics",
//         "Tenant screening",
//         "Automated rent collection",
//       ],
//     },
//     {
//       name: "Gold",
//       icon: <Gem className="w-6 h-6" />,
//       priceMonthly: 3000,
//       priceYearly: 9000,
//       properties: 4,
//       rooms: 70,
//       vacancyListings: 4,
//       topOffers: 2,
//       trial: true,
//       current: activeSub?.tier === "Silver",
//       description: "Most popular for professional managers",
//       features: [
//         "Premium listing visibility",
//         "Maintenance tracking",
//         "Financial reporting",
//       ],
//     },
//     {
//       name: "Diamond",
//       icon: <Crown className="w-6 h-6" />,
//       priceMonthly: 5000,
//       priceYearly: 15000,
//       properties: 4,
//       rooms: 1000,
//       vacancyListings: "Unlimited",
//       topOffers: "Unlimited",
//       trial: true,
//       current: activeSub?.tier === "Diamond",
//       description: "Enterprise-grade solution",
//       features: [
//         "Dedicated account manager",
//         "Custom API access",
//         "Priority support",
//       ],
//     },
//   ];
